# Generated by Django 5.2.6 on 2025-11-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_certificate_trainingmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='target_programs',
            field=models.CharField(default='ALL', help_text='Comma-separated programs (e.g., "BSIT,BSCS") or "ALL" for all programs', max_length=200),
        ),
    ]
