# Generated by Django 5.2.6 on 2025-11-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_materials',
            field=models.ManyToManyField(blank=True, related_name='completed_by_enrollments', to='dashboard.trainingmaterial'),
        ),
    ]
