# Generated by Django 5.2.6 on 2025-11-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_enrollment_completed_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmaterial',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes', null=True),
        ),
    ]
