# Generated by Django 5.2.6 on 2025-12-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_taskdeadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourse',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='URL to course thumbnail in Supabase storage', max_length=500, null=True),
        ),
    ]
