# Generated by Django 5.2.6 on 2025-12-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_trainingcourse_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether the quiz is ready for users to take'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='target_question_count',
            field=models.PositiveIntegerField(default=10, help_text='Number of questions to add'),
        ),
    ]
