# Generated by Django 5.2.6 on 2025-12-10 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_add_quiz_publishing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('event', 'Event'), ('task', 'Task'), ('reminder', 'Reminder')], default='event', max_length=20)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reminder_minutes', models.IntegerField(choices=[(0, 'At time of event'), (5, '5 minutes before'), (15, '15 minutes before'), (30, '30 minutes before'), (60, '1 hour before'), (1440, '1 day before')], default=15, help_text='When to send reminder notification')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('color', models.CharField(default='#667eea', help_text='Event color in hex format', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date', 'event_time'],
            },
        ),
    ]
