# Generated by Django 5.2.6 on 2025-11-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='program',
            field=models.CharField(blank=True, choices=[('BSIT', 'BS Information Technology'), ('BSCS', 'BS Computer Science'), ('BSARCH', 'BS Architecture'), ('BSCE', 'BS Civil Engineering'), ('BSME', 'BS Mechanical Engineering'), ('BSEE', 'BS Electrical Engineering'), ('BSBA', 'BS Business Administration'), ('BSED', 'BS Education'), ('BSHRM', 'BS Hotel & Restaurant Management'), ('BSTM', 'BS Tourism Management'), ('OTHER', 'Other')], help_text='For students: degree program. For employees: area of expertise', max_length=20),
        ),
    ]
