# Generated by Django 5.2.6 on 2025-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='URL to profile picture in Supabase storage', max_length=500, null=True),
        ),
    ]
