# Generated by Django 5.2.6 on 2025-11-30 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_enrollment', models.BooleanField(default=True, help_text='Receive email when enrolled in a course')),
                ('email_on_completion', models.BooleanField(default=True, help_text='Receive email when you complete a course')),
                ('email_on_certificate', models.BooleanField(default=True, help_text='Receive email when a certificate is issued')),
                ('email_on_assignment', models.BooleanField(default=True, help_text='Receive email when training is assigned to you')),
                ('email_on_reminder', models.BooleanField(default=True, help_text='Receive reminder emails')),
                ('notify_on_enrollment', models.BooleanField(default=True, help_text='Show notification when enrolled in a course')),
                ('notify_on_completion', models.BooleanField(default=True, help_text='Show notification when you complete a course')),
                ('notify_on_certificate', models.BooleanField(default=True, help_text='Show notification when a certificate is issued')),
                ('notify_on_assignment', models.BooleanField(default=True, help_text='Show notification when training is assigned to you')),
                ('notify_on_reminder', models.BooleanField(default=True, help_text='Show reminder notifications')),
                ('notify_on_announcement', models.BooleanField(default=True, help_text='Show announcement notifications')),
                ('daily_digest', models.BooleanField(default=False, help_text='Receive daily summary of notifications via email')),
                ('weekly_digest', models.BooleanField(default=False, help_text='Receive weekly summary of notifications via email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
